name: Deploy Angular via FTP

on:
  push:
    branches:
      - master  # Change en 'master' si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change selon ta version Angular

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🔨 Build du projet Angular
        run: npm run build -- --configuration=production

      - name: 🚀 Déployer via FTP
        uses: sebastianpopp/ftp-action@v1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/daymond_client/browser/  # Remplace par le bon dossier
         # server-dir: "/sites/test.daymondboutique.com/"  # Remplace par ton dossier de production sur le serveur
          remote-dir: /sites/test.daymondboutique.com  # Le répertoire distant de ton serveur

          # Crée un dossier de sauvegarde avec la date et déplace les anciens fichiers
          remote-backup-dir: /sites/test.daymondboutique.com/backup/$(date +%Y-%m-%d_%H-%M-%S)  # Dossier de backup avec timestamp
          backup: true  # Utilise ce paramètre pour déplacer les fichiers dans un dossier de backup avant le déploiement
